-- =============================================================================
-- 09_seed_song_moments.sql
-- Relacion N:M cancion <-> momento_liturgico.
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM cancion_momento)
BEGIN
    DECLARE @pares TABLE (titulo VARCHAR(256), autor VARCHAR(256), slug_momento VARCHAR(50))

    INSERT INTO @pares(titulo, autor, slug_momento) VALUES
        ('Canon en Re mayor', 'Johann Pachelbel', 'entrada_novio'),
        ('Marcha del Príncipe de Dinamarca', 'Jeremiah Clarke', 'entrada_novio'),
        ('Pompa y Circunstancia', 'Edward Elgar', 'entrada_novio'),
        ('Marcha nupcial de la Princesa Sofía', 'Tradicional', 'entrada_novio'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'entrada_novio'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'entrada_novio'),
        ('Trumpet Voluntary', 'Jeremiah Clarke', 'entrada_novio'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'entrada_novio'),
        ('Mi corazón encantado', 'César Franco', 'entrada_novio'),
        ('Mi corazón encantado', 'César Franco', 'fotografias'),
        ('Marcha nupcial', 'Felix Mendelssohn', 'entrada_novia'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'entrada_novia'),
        ('Ave María (instrumental)', 'Charles Gounod', 'entrada_novia'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'entrada_novia'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'fotografias'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'entrada_novia'),
        ('Dios Trino', 'Marco López', 'entrada_novio'),
        ('Dios Trino', 'Marco López', 'entrada_novia'),
        ('Vosotros sois de Dios', 'Focolares', 'entrada_novio'),
        ('Vosotros sois de Dios', 'Focolares', 'entrada_novia'),
        ('Engalanada', 'Tradicional litúrgico', 'entrada_novia'),
        ('Piedad', 'Coro Pacem Deus', 'piedad'),
        ('Señor ten piedad', 'Grial', 'piedad'),
        ('De nosotros ten piedad', 'Tradicional litúrgico', 'piedad'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'piedad'),
        ('Kyrie Eleison', 'Comunidad Shalom', 'piedad'),
        ('Piedad — Kyrie', 'Cantaré', 'piedad'),
        ('Piedad Sinaí', 'Sinaí', 'piedad'),
        ('Cristo ten piedad', 'Tradicional litúrgico', 'piedad'),
        ('Señor, mi señor, ten piedad', 'Tradicional litúrgico', 'piedad'),
        ('Gloria Giombini', 'Giombini', 'gloria'),
        ('Gloria Palazón', 'Francisco Palazón', 'gloria'),
        ('En las alturas', 'Tradicional litúrgico', 'gloria'),
        ('Gloria al Señor', 'Tradicional litúrgico', 'gloria'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Salmo de la Creación', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Tu palabra me da vida', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Sacramento de Amor', 'Sinaí', 'salmo_responsorial'),
        ('Aleluya (Kairoi)', 'Kairoi', 'aleluya'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'aleluya'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'aclamacion'),
        ('Aleluya (Cantaré)', 'Cantaré', 'aleluya'),
        ('Busca primero', 'Karen Lafferty', 'aleluya'),
        ('Aleluya (Verbum Panis)', 'Verbum Panis', 'aleluya'),
        ('Cristo vive en mí', 'Tradicional litúrgico', 'aleluya'),
        ('Yo creo en la palabra de Dios', 'Tradicional litúrgico', 'aclamacion'),
        ('Reunidos en el nombre del Señor', 'Francisco Palazón', 'ofertorio'),
        ('Esto que te doy, es vino y pan, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('Te ofrecemos, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('Sobre tu altar', 'Tradicional litúrgico', 'ofertorio'),
        ('Recíbeme', 'Tradicional litúrgico', 'ofertorio'),
        ('Con amor te presento, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('En su mesa hay amor', 'Tradicional litúrgico', 'ofertorio'),
        ('Tomad, Señor, y recibid', 'S. Ignacio de Loyola', 'ofertorio'),
        ('Cristo mío', 'Tradicional litúrgico', 'ofertorio'),
        ('Son para ti', 'Tradicional litúrgico', 'ofertorio'),
        ('Vino y pan', 'Tradicional litúrgico', 'ofertorio'),
        ('Con estas ofrendas', 'Tradicional litúrgico', 'ofertorio'),
        ('Panis Angelicus', 'César Franck', 'ofertorio'),
        ('Panis Angelicus', 'César Franck', 'comunion'),
        ('Santo Luna', 'A. Luna', 'santo'),
        ('Santo Palestra', 'Palestra', 'santo'),
        ('Santo Giombini', 'Giombini', 'santo'),
        ('Santo Mejía', 'Alejandro Mejía', 'santo'),
        ('¡Oh Cordero de Dios!', 'Tradicional litúrgico', 'cordero'),
        ('Cordero Mejía', 'Alejandro Mejía', 'cordero'),
        ('Cordero (Comunidad Sta. María)', 'Comunidad Sta. María', 'cordero'),
        ('Cordero Dynamis', 'Dynamis', 'cordero'),
        ('Cordero 2020', 'Tradicional litúrgico', 'cordero'),
        ('Divino Manjar', 'Tradicional litúrgico', 'comunion'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'comunion'),
        ('El amor de mi Dios', 'Hna. Inés de Jesús', 'comunion'),
        ('Por Amor', 'Tradicional litúrgico', 'comunion'),
        ('¡Oh Buen Jesús!', 'Tradicional litúrgico', 'comunion'),
        ('Pan de vida, pan de fe', 'Tradicional litúrgico', 'comunion'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'comunion'),
        ('Me has seducido, Señor', 'Tradicional litúrgico', 'comunion'),
        ('Verbum Panis', 'Verbum Panis', 'comunion'),
        ('Alma de Cristo', 'Tradicional litúrgico', 'comunion'),
        ('Ya no eres pan y vino', 'Jorge Luis Bohórquez', 'comunion'),
        ('Ave María Solidaria', 'Tradicional litúrgico', 'comunion'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'comunion'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'salida'),
        ('Tus Maravillas', 'Verbum Panis', 'comunion'),
        ('Tus Maravillas', 'Verbum Panis', 'salida'),
        ('Ave María', 'Franz Schubert', 'firma_pliego'),
        ('Ave María', 'Franz Schubert', 'salida'),
        ('Ave María', 'Verbum Panis', 'firma_pliego'),
        ('Ave María', 'Verbum Panis', 'salida'),
        ('Juramento', 'Tradicional litúrgico', 'firma_pliego'),
        ('Hoy he vuelto', 'Cesáreo Gabaráin', 'salida'),
        ('No voy a decirte adiós', 'Alfareros', 'salida'),
        ('Toda Hermosa', 'Hna. Inés de Jesús', 'salida'),
        ('Toma mi mano', 'Alfareros', 'salida'),
        ('Rezo por ti', 'Tradicional litúrgico', 'salida'),
        ('Madre del Silencio', 'Tradicional litúrgico', 'salida'),
        ('María Tú', 'Tradicional litúrgico', 'salida'),
        ('De aquí hasta el final', 'Tradicional', 'salida'),
        ('De aquí hasta el final', 'Tradicional', 'fotografias'),
        ('Marcha Nupcial Wagner', 'Richard Wagner', 'salida'),
        ('Perfect', 'Ed Sheeran', 'fotografias'),
        ('Perfect', 'Ed Sheeran', 'salida'),
        ('A Thousand Years', 'Christina Perri', 'fotografias'),
        ('A Thousand Years', 'Christina Perri', 'salida'),
        ('Thinking Out Loud', 'Ed Sheeran', 'fotografias'),
        ('Thinking Out Loud', 'Ed Sheeran', 'salida'),
        ('All of Me', 'John Legend', 'fotografias'),
        ('All of Me', 'John Legend', 'salida'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'fotografias'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'salida'),
        ('Marry You', 'Bruno Mars', 'fotografias'),
        ('Marry You', 'Bruno Mars', 'salida'),
        ('You Raise Me Up', 'Josh Groban', 'fotografias'),
        ('You Raise Me Up', 'Josh Groban', 'salida'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'fotografias'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'salida'),
        ('Stand by Me', 'Ben E. King', 'fotografias'),
        ('Stand by Me', 'Ben E. King', 'salida'),
        ('Treasure', 'Bruno Mars', 'fotografias'),
        ('Treasure', 'Bruno Mars', 'salida'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'fotografias'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'salida'),
        ('Kiss Me', 'Sixpence None the Richer', 'fotografias'),
        ('Kiss Me', 'Sixpence None the Richer', 'salida'),
        ('Best Day of My Life', 'American Authors', 'fotografias'),
        ('Best Day of My Life', 'American Authors', 'salida'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'fotografias'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'salida'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'fotografias'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'salida'),
        ('Sunday Morning', 'Maroon 5', 'fotografias'),
        ('Sunday Morning', 'Maroon 5', 'salida'),
        ('Sugar', 'Maroon 5', 'fotografias'),
        ('Sugar', 'Maroon 5', 'salida'),
        ('Game of Love', 'Wayne Fontana', 'fotografias'),
        ('Game of Love', 'Wayne Fontana', 'salida'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'fotografias'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'salida'),
        ('At Last', 'Etta James', 'fotografias'),
        ('At Last', 'Etta James', 'salida'),
        ('Wonderful Tonight', 'Eric Clapton', 'fotografias'),
        ('Wonderful Tonight', 'Eric Clapton', 'salida'),
        ('Your Song', 'Elton John', 'fotografias'),
        ('Your Song', 'Elton John', 'salida'),
        ('Make You Feel My Love', 'Adele', 'fotografias'),
        ('Make You Feel My Love', 'Adele', 'salida'),
        ('I Loved Her First', 'Heartland', 'fotografias'),
        ('From This Moment On', 'Shania Twain', 'fotografias'),
        ('From This Moment On', 'Shania Twain', 'salida'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'fotografias'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'salida'),
        ('Everything', 'Michael Bublé', 'fotografias'),
        ('Everything', 'Michael Bublé', 'salida'),
        ('I''m Yours', 'Jason Mraz', 'fotografias'),
        ('I''m Yours', 'Jason Mraz', 'salida'),
        ('Better Together', 'Jack Johnson', 'fotografias'),
        ('Better Together', 'Jack Johnson', 'salida'),
        ('Say You Won''t Let Go', 'James Arthur', 'fotografias'),
        ('Say You Won''t Let Go', 'James Arthur', 'salida'),
        ('My Girl', 'The Temptations', 'fotografias'),
        ('La Vie en Rose', 'Édith Piaf', 'fotografias'),
        ('La Vie en Rose', 'Édith Piaf', 'salida'),
        ('Unchained Melody', 'The Righteous Brothers', 'fotografias'),
        ('Unchained Melody', 'The Righteous Brothers', 'salida'),
        ('Have I Told You Lately', 'Van Morrison', 'fotografias'),
        ('When You Say Nothing at All', 'Ronan Keating', 'fotografias'),
        ('When You Say Nothing at All', 'Ronan Keating', 'salida'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'fotografias'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'salida'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'fotografias'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'salida'),
        ('Hasta mi final', 'Il Divo', 'fotografias'),
        ('Hasta mi final', 'Il Divo', 'salida'),
        ('Un mismo corazón', 'Tradicional', 'fotografias'),
        ('Un mismo corazón', 'Tradicional', 'salida'),
        ('Amor Eterno', 'Juan Gabriel', 'fotografias'),
        ('Amor Eterno', 'Juan Gabriel', 'salida'),
        ('Una madre no se cansa de olvidar', 'Tradicional', 'fotografias'),
        ('Te diré que sí', 'Edith Aravena', 'fotografias'),
        ('Te diré que sí', 'Edith Aravena', 'salida'),
        ('Cuando llego a casa', 'Fonseca', 'fotografias'),
        ('Cuando llego a casa', 'Fonseca', 'salida'),
        ('Regalo del Cielo', 'Athenas', 'fotografias'),
        ('Regalo del Cielo', 'Athenas', 'salida'),
        ('Por ti seré', 'Il Divo', 'fotografias'),
        ('Por ti seré', 'Il Divo', 'salida'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'fotografias'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'salida'),
        ('Contigo aprendí', 'Armando Manzanero', 'fotografias'),
        ('Hoy tengo ganas de ti', 'Alejandro Fernández', 'fotografias'),
        ('Tu poeta', 'Alex Campos', 'fotografias'),
        ('Tu poeta', 'Alex Campos', 'salida'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'fotografias'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'salida'),
        ('Estoy hecho de pedacitos de ti', 'Antonio Orozco', 'fotografias'),
        ('Solamente tú', 'Pablo Alborán', 'fotografias'),
        ('Solamente tú', 'Pablo Alborán', 'salida'),
        ('Cómo te extraño', 'Leo Dan', 'fotografias'),
        ('Por ti volaré', 'Andrea Bocelli', 'fotografias'),
        ('Por ti volaré', 'Andrea Bocelli', 'salida'),
        ('Bésame mucho', 'Consuelo Velázquez', 'fotografias'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'fotografias'),
        ('Sabor a mí', 'Álvaro Carrillo', 'fotografias'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'fotografias'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'entrada_novio'),
        ('La Rejouissance', 'G.F. Haendel', 'entrada_novio'),
        ('Trumpet Tune', 'Henry Purcell', 'entrada_novio'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'entrada_novio'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'entrada_novia'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'entrada_novio'),
        ('Minueto en Sol', 'Luigi Boccherini', 'entrada_novio'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'entrada_novio'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'entrada_novia'),
        ('Delante del altar', 'Joel Cruz', 'entrada_novio'),
        ('Aclaró', 'Tradicional litúrgico', 'entrada_novio'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'entrada_novia'),
        ('O mio babbino caro', 'Giacomo Puccini', 'entrada_novia'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'entrada_novia'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'salida'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'entrada_novia'),
        ('Meditación de Thaïs', 'Jules Massenet', 'entrada_novia'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'entrada_novia'),
        ('Rivers Flows in You', 'Yiruma', 'entrada_novia'),
        ('Rivers Flows in You', 'Yiruma', 'fotografias'),
        ('Only Time', 'Enya', 'entrada_novia'),
        ('Only Time', 'Enya', 'salida'),
        ('Ven amada mía', 'Tradicional litúrgico', 'entrada_novia'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'entrada_novia'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'piedad'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'piedad'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'piedad'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'piedad'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'piedad'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'piedad'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'piedad'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'gloria'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'gloria'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'salmo_responsorial'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'aleluya'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'aleluya'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'aleluya'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'comunion'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'aleluya'),
        ('Dios está aquí', 'Tradicional litúrgico', 'aleluya'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'aleluya'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'aleluya'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'aleluya'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'aleluya'),
        ('Oración por la Familia', 'Padre Zezinho', 'ofertorio'),
        ('Oración por la Familia', 'Padre Zezinho', 'comunion'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'ofertorio'),
        ('Ante tu altar', 'Walmir Alencar', 'ofertorio'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'ofertorio'),
        ('Cinco panes', 'Tradicional litúrgico', 'ofertorio'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'ofertorio'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'ofertorio'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'comunion'),
        ('Tómame', 'Tradicional litúrgico', 'ofertorio'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'ofertorio'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'santo'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'santo'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'santo'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'santo'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'santo'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'santo'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'cordero'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'cordero'),
        ('Un pacto con Dios', 'Rabito', 'comunion'),
        ('Alianza Eterna', 'Hermana Glenda', 'comunion'),
        ('Alianza Eterna', 'Hermana Glenda', 'firma_pliego'),
        ('Nadie te ama como yo', 'Martín Valverde', 'comunion'),
        ('Cerca de ti, Señor', 'Tradicional', 'comunion'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'comunion'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'comunion'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'comunion'),
        ('Nada te turbe', 'Comunidad de Taizé', 'comunion'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'comunion'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'comunion'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'comunion'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'comunion'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'comunion'),
        ('Madre del amor', 'Cristóbal Fones', 'comunion'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'salida'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'salida'),
        ('María de la Alianza', 'Tradicional litúrgico', 'salida'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'salida'),
        ('María, mírame', 'Tradicional litúrgico', 'salida'),
        ('Salve Regina', 'Canto Gregoriano', 'salida'),
        ('Ave María', 'Giulio Caccini', 'salida'),
        ('Ave María', 'Giulio Caccini', 'firma_pliego'),
        ('Ave María', 'Giulio Caccini', 'comunion'),
        ('Senza Catene', 'Il Divo', 'firma_pliego'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'firma_pliego'),
        ('Serenata', 'Franz Schubert', 'firma_pliego'),
        ('Algo contigo', 'Rita Páez', 'fotografias'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'fotografias'),
        ('Birds of a Feather', 'Billie Eilish', 'fotografias'),
        ('Birds of a Feather', 'Billie Eilish', 'salida'),
        ('Bubbly', 'Colbie Caillat', 'fotografias'),
        ('Close to You', 'Carpenters', 'fotografias'),
        ('Dream a Little Dream of Me', 'Doris Day', 'fotografias'),
        ('Eres para mí', 'Julieta Venegas', 'fotografias'),
        ('Es por ti', 'Juanes', 'fotografias'),
        ('From the Start', 'Laufey', 'fotografias'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'fotografias'),
        ('Juntos', 'Paloma San Basilio', 'fotografias'),
        ('Juntos', 'Paloma San Basilio', 'salida'),
        ('More Than Words', 'Extreme', 'fotografias'),
        ('She Will Be Loved', 'Maroon 5', 'fotografias'),
        ('True Colors', 'Cyndi Lauper', 'fotografias'),
        ('Unforgettable', 'Nat King Cole', 'fotografias'),
        ('Yo quisiera', 'Reik', 'fotografias'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'fotografias'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'salida'),
        ('One of Us', 'Joan Osborne', 'fotografias')

    INSERT INTO cancion_momento(id_cancion, id_momento)
    SELECT s.id_cancion, m.id_momento
    FROM @pares p
    INNER JOIN cancion s ON s.titulo = p.titulo AND s.autor = p.autor
    INNER JOIN momento_liturgico m ON m.slug = p.slug_momento
END
GO

PRINT 'Pares cancion-momento: ' + CAST((SELECT COUNT(*) FROM cancion_momento) AS VARCHAR)
GO
