-- =============================================================================
-- 10_seed_song_requirements.sql
-- Requerimientos instrumentales por cancion.
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM cancion_requerimiento)
BEGIN
    DECLARE @reqs TABLE (titulo VARCHAR(256), autor VARCHAR(256), slug_inst VARCHAR(50), tipo VARCHAR(15))

    INSERT INTO @reqs(titulo, autor, slug_inst, tipo) VALUES
        ('Canon en Re mayor', 'Johann Pachelbel', 'piano', 'MINIMUM'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'violin_1', 'MINIMUM'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'violin_2', 'MINIMUM'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'piano', 'OPTIMAL'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'violin_1', 'OPTIMAL'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'violin_2', 'OPTIMAL'),
        ('Canon en Re mayor', 'Johann Pachelbel', 'cello', 'OPTIMAL'),
        ('Marcha del Príncipe de Dinamarca', 'Jeremiah Clarke', 'piano', 'MINIMUM'),
        ('Marcha del Príncipe de Dinamarca', 'Jeremiah Clarke', 'piano', 'OPTIMAL'),
        ('Marcha del Príncipe de Dinamarca', 'Jeremiah Clarke', 'violin_1', 'OPTIMAL'),
        ('Marcha del Príncipe de Dinamarca', 'Jeremiah Clarke', 'violin_2', 'OPTIMAL'),
        ('Pompa y Circunstancia', 'Edward Elgar', 'piano', 'MINIMUM'),
        ('Pompa y Circunstancia', 'Edward Elgar', 'piano', 'OPTIMAL'),
        ('Pompa y Circunstancia', 'Edward Elgar', 'violin_1', 'OPTIMAL'),
        ('Pompa y Circunstancia', 'Edward Elgar', 'cello', 'OPTIMAL'),
        ('Marcha nupcial de la Princesa Sofía', 'Tradicional', 'piano', 'MINIMUM'),
        ('Marcha nupcial de la Princesa Sofía', 'Tradicional', 'piano', 'OPTIMAL'),
        ('Marcha nupcial de la Princesa Sofía', 'Tradicional', 'violin_1', 'OPTIMAL'),
        ('Marcha nupcial de la Princesa Sofía', 'Tradicional', 'violin_2', 'OPTIMAL'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'piano', 'MINIMUM'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'piano', 'OPTIMAL'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'violin_1', 'OPTIMAL'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'violin_2', 'OPTIMAL'),
        ('Jesús, alegría de los hombres', 'J.S. Bach', 'cello', 'OPTIMAL'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'piano', 'MINIMUM'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'violin_1', 'MINIMUM'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'piano', 'OPTIMAL'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'violin_1', 'OPTIMAL'),
        ('Aria de la Suite en Re', 'J.S. Bach', 'cello', 'OPTIMAL'),
        ('Trumpet Voluntary', 'Jeremiah Clarke', 'piano', 'MINIMUM'),
        ('Trumpet Voluntary', 'Jeremiah Clarke', 'piano', 'OPTIMAL'),
        ('Trumpet Voluntary', 'Jeremiah Clarke', 'violin_1', 'OPTIMAL'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'piano', 'MINIMUM'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'violin_1', 'MINIMUM'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'piano', 'OPTIMAL'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'violin_1', 'OPTIMAL'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'violin_2', 'OPTIMAL'),
        ('Spring (La Primavera)', 'Antonio Vivaldi', 'cello', 'OPTIMAL'),
        ('Mi corazón encantado', 'César Franco', 'piano', 'MINIMUM'),
        ('Mi corazón encantado', 'César Franco', 'voz_femenina', 'MINIMUM'),
        ('Mi corazón encantado', 'César Franco', 'piano', 'OPTIMAL'),
        ('Mi corazón encantado', 'César Franco', 'voz_femenina', 'OPTIMAL'),
        ('Marcha nupcial', 'Felix Mendelssohn', 'piano', 'MINIMUM'),
        ('Marcha nupcial', 'Felix Mendelssohn', 'piano', 'OPTIMAL'),
        ('Marcha nupcial', 'Felix Mendelssohn', 'violin_1', 'OPTIMAL'),
        ('Marcha nupcial', 'Felix Mendelssohn', 'violin_2', 'OPTIMAL'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'piano', 'MINIMUM'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'voz_femenina', 'MINIMUM'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'piano', 'OPTIMAL'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'voz_femenina', 'OPTIMAL'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'violin_1', 'OPTIMAL'),
        ('Medley Marcha Nupcial / Aleluya cantado', 'Mendelssohn / Cohen', 'violin_2', 'OPTIMAL'),
        ('Ave María (instrumental)', 'Charles Gounod', 'piano', 'MINIMUM'),
        ('Ave María (instrumental)', 'Charles Gounod', 'violin_1', 'MINIMUM'),
        ('Ave María (instrumental)', 'Charles Gounod', 'piano', 'OPTIMAL'),
        ('Ave María (instrumental)', 'Charles Gounod', 'violin_1', 'OPTIMAL'),
        ('Ave María (instrumental)', 'Charles Gounod', 'cello', 'OPTIMAL'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'piano', 'MINIMUM'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'voz_femenina', 'MINIMUM'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'piano', 'OPTIMAL'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'voz_femenina', 'OPTIMAL'),
        ('Can''t Help Falling in Love (instrumental)', 'Elvis Presley', 'violin_1', 'OPTIMAL'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'piano', 'MINIMUM'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'violin_1', 'MINIMUM'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'piano', 'OPTIMAL'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'violin_1', 'OPTIMAL'),
        ('A Thousand Years (instrumental)', 'Christina Perri', 'cello', 'OPTIMAL'),
        ('Dios Trino', 'Marco López', 'piano', 'MINIMUM'),
        ('Dios Trino', 'Marco López', 'voz_femenina', 'MINIMUM'),
        ('Dios Trino', 'Marco López', 'piano', 'OPTIMAL'),
        ('Dios Trino', 'Marco López', 'voz_femenina', 'OPTIMAL'),
        ('Dios Trino', 'Marco López', 'violin_1', 'OPTIMAL'),
        ('Vosotros sois de Dios', 'Focolares', 'piano', 'MINIMUM'),
        ('Vosotros sois de Dios', 'Focolares', 'voz_femenina', 'MINIMUM'),
        ('Vosotros sois de Dios', 'Focolares', 'piano', 'OPTIMAL'),
        ('Vosotros sois de Dios', 'Focolares', 'voz_femenina', 'OPTIMAL'),
        ('Engalanada', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Engalanada', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Engalanada', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Engalanada', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Engalanada', 'Tradicional litúrgico', 'violin_1', 'OPTIMAL'),
        ('Piedad', 'Coro Pacem Deus', 'piano', 'MINIMUM'),
        ('Piedad', 'Coro Pacem Deus', 'voz_femenina', 'MINIMUM'),
        ('Piedad', 'Coro Pacem Deus', 'piano', 'OPTIMAL'),
        ('Piedad', 'Coro Pacem Deus', 'voz_femenina', 'OPTIMAL'),
        ('Señor ten piedad', 'Grial', 'piano', 'MINIMUM'),
        ('Señor ten piedad', 'Grial', 'voz_femenina', 'MINIMUM'),
        ('Señor ten piedad', 'Grial', 'piano', 'OPTIMAL'),
        ('Señor ten piedad', 'Grial', 'voz_femenina', 'OPTIMAL'),
        ('De nosotros ten piedad', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('De nosotros ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('De nosotros ten piedad', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('De nosotros ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'piano', 'MINIMUM'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'voz_femenina', 'MINIMUM'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'piano', 'OPTIMAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'voz_femenina', 'OPTIMAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'violin_1', 'OPTIMAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'cello', 'OPTIMAL'),
        ('Kyrie Eleison', 'Comunidad Shalom', 'piano', 'MINIMUM'),
        ('Kyrie Eleison', 'Comunidad Shalom', 'voz_femenina', 'MINIMUM'),
        ('Kyrie Eleison', 'Comunidad Shalom', 'piano', 'OPTIMAL'),
        ('Kyrie Eleison', 'Comunidad Shalom', 'voz_femenina', 'OPTIMAL'),
        ('Piedad — Kyrie', 'Cantaré', 'piano', 'MINIMUM'),
        ('Piedad — Kyrie', 'Cantaré', 'voz_femenina', 'MINIMUM'),
        ('Piedad — Kyrie', 'Cantaré', 'piano', 'OPTIMAL'),
        ('Piedad — Kyrie', 'Cantaré', 'voz_femenina', 'OPTIMAL'),
        ('Piedad Sinaí', 'Sinaí', 'piano', 'MINIMUM'),
        ('Piedad Sinaí', 'Sinaí', 'voz_femenina', 'MINIMUM'),
        ('Piedad Sinaí', 'Sinaí', 'piano', 'OPTIMAL'),
        ('Piedad Sinaí', 'Sinaí', 'voz_femenina', 'OPTIMAL'),
        ('Cristo ten piedad', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cristo ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cristo ten piedad', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cristo ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Señor, mi señor, ten piedad', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Señor, mi señor, ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Señor, mi señor, ten piedad', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Señor, mi señor, ten piedad', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Gloria Giombini', 'Giombini', 'piano', 'MINIMUM'),
        ('Gloria Giombini', 'Giombini', 'voz_femenina', 'MINIMUM'),
        ('Gloria Giombini', 'Giombini', 'piano', 'OPTIMAL'),
        ('Gloria Giombini', 'Giombini', 'voz_femenina', 'OPTIMAL'),
        ('Gloria Palazón', 'Francisco Palazón', 'piano', 'MINIMUM'),
        ('Gloria Palazón', 'Francisco Palazón', 'voz_femenina', 'MINIMUM'),
        ('Gloria Palazón', 'Francisco Palazón', 'piano', 'OPTIMAL'),
        ('Gloria Palazón', 'Francisco Palazón', 'voz_femenina', 'OPTIMAL'),
        ('En las alturas', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('En las alturas', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('En las alturas', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('En las alturas', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Gloria al Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Gloria al Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Gloria al Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Gloria al Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Si yo no tengo Amor', 'Tradicional litúrgico', 'violin_1', 'OPTIMAL'),
        ('Salmo de la Creación', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Salmo de la Creación', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Salmo de la Creación', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Salmo de la Creación', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Tu palabra me da vida', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Tu palabra me da vida', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Tu palabra me da vida', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Tu palabra me da vida', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Sacramento de Amor', 'Sinaí', 'piano', 'MINIMUM'),
        ('Sacramento de Amor', 'Sinaí', 'voz_femenina', 'MINIMUM'),
        ('Sacramento de Amor', 'Sinaí', 'piano', 'OPTIMAL'),
        ('Sacramento de Amor', 'Sinaí', 'voz_femenina', 'OPTIMAL'),
        ('Aleluya (Kairoi)', 'Kairoi', 'piano', 'MINIMUM'),
        ('Aleluya (Kairoi)', 'Kairoi', 'voz_femenina', 'MINIMUM'),
        ('Aleluya (Kairoi)', 'Kairoi', 'piano', 'OPTIMAL'),
        ('Aleluya (Kairoi)', 'Kairoi', 'voz_femenina', 'OPTIMAL'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Aclamación — Gloria a ti, Cristo', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Aleluya (Cantaré)', 'Cantaré', 'piano', 'MINIMUM'),
        ('Aleluya (Cantaré)', 'Cantaré', 'voz_femenina', 'MINIMUM'),
        ('Aleluya (Cantaré)', 'Cantaré', 'piano', 'OPTIMAL'),
        ('Aleluya (Cantaré)', 'Cantaré', 'voz_femenina', 'OPTIMAL'),
        ('Busca primero', 'Karen Lafferty', 'piano', 'MINIMUM'),
        ('Busca primero', 'Karen Lafferty', 'voz_femenina', 'MINIMUM'),
        ('Busca primero', 'Karen Lafferty', 'piano', 'OPTIMAL'),
        ('Busca primero', 'Karen Lafferty', 'voz_femenina', 'OPTIMAL'),
        ('Aleluya (Verbum Panis)', 'Verbum Panis', 'piano', 'MINIMUM'),
        ('Aleluya (Verbum Panis)', 'Verbum Panis', 'voz_femenina', 'MINIMUM'),
        ('Aleluya (Verbum Panis)', 'Verbum Panis', 'piano', 'OPTIMAL'),
        ('Aleluya (Verbum Panis)', 'Verbum Panis', 'voz_femenina', 'OPTIMAL'),
        ('Cristo vive en mí', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cristo vive en mí', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cristo vive en mí', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cristo vive en mí', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Yo creo en la palabra de Dios', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Yo creo en la palabra de Dios', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Yo creo en la palabra de Dios', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Yo creo en la palabra de Dios', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Reunidos en el nombre del Señor', 'Francisco Palazón', 'piano', 'MINIMUM'),
        ('Reunidos en el nombre del Señor', 'Francisco Palazón', 'voz_femenina', 'MINIMUM'),
        ('Reunidos en el nombre del Señor', 'Francisco Palazón', 'piano', 'OPTIMAL'),
        ('Reunidos en el nombre del Señor', 'Francisco Palazón', 'voz_femenina', 'OPTIMAL'),
        ('Esto que te doy, es vino y pan, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Esto que te doy, es vino y pan, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Esto que te doy, es vino y pan, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Esto que te doy, es vino y pan, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Te ofrecemos, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Te ofrecemos, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Te ofrecemos, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Te ofrecemos, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Sobre tu altar', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Sobre tu altar', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Sobre tu altar', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Sobre tu altar', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Recíbeme', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Recíbeme', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Recíbeme', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Recíbeme', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Con amor te presento, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Con amor te presento, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Con amor te presento, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Con amor te presento, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('En su mesa hay amor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('En su mesa hay amor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('En su mesa hay amor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('En su mesa hay amor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Tomad, Señor, y recibid', 'S. Ignacio de Loyola', 'piano', 'MINIMUM'),
        ('Tomad, Señor, y recibid', 'S. Ignacio de Loyola', 'voz_femenina', 'MINIMUM'),
        ('Tomad, Señor, y recibid', 'S. Ignacio de Loyola', 'piano', 'OPTIMAL'),
        ('Tomad, Señor, y recibid', 'S. Ignacio de Loyola', 'voz_femenina', 'OPTIMAL'),
        ('Cristo mío', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cristo mío', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cristo mío', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cristo mío', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Son para ti', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Son para ti', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Son para ti', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Son para ti', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Vino y pan', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Vino y pan', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Vino y pan', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Vino y pan', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Con estas ofrendas', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Con estas ofrendas', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Con estas ofrendas', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Con estas ofrendas', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Panis Angelicus', 'César Franck', 'piano', 'MINIMUM'),
        ('Panis Angelicus', 'César Franck', 'voz_femenina', 'MINIMUM'),
        ('Panis Angelicus', 'César Franck', 'piano', 'OPTIMAL'),
        ('Panis Angelicus', 'César Franck', 'voz_femenina', 'OPTIMAL'),
        ('Panis Angelicus', 'César Franck', 'violin_1', 'OPTIMAL'),
        ('Panis Angelicus', 'César Franck', 'cello', 'OPTIMAL'),
        ('Santo Luna', 'A. Luna', 'piano', 'MINIMUM'),
        ('Santo Luna', 'A. Luna', 'voz_femenina', 'MINIMUM'),
        ('Santo Luna', 'A. Luna', 'piano', 'OPTIMAL'),
        ('Santo Luna', 'A. Luna', 'voz_femenina', 'OPTIMAL'),
        ('Santo Palestra', 'Palestra', 'piano', 'MINIMUM'),
        ('Santo Palestra', 'Palestra', 'voz_femenina', 'MINIMUM'),
        ('Santo Palestra', 'Palestra', 'piano', 'OPTIMAL'),
        ('Santo Palestra', 'Palestra', 'voz_femenina', 'OPTIMAL'),
        ('Santo Giombini', 'Giombini', 'piano', 'MINIMUM'),
        ('Santo Giombini', 'Giombini', 'voz_femenina', 'MINIMUM'),
        ('Santo Giombini', 'Giombini', 'piano', 'OPTIMAL'),
        ('Santo Giombini', 'Giombini', 'voz_femenina', 'OPTIMAL'),
        ('Santo Mejía', 'Alejandro Mejía', 'piano', 'MINIMUM'),
        ('Santo Mejía', 'Alejandro Mejía', 'voz_femenina', 'MINIMUM'),
        ('Santo Mejía', 'Alejandro Mejía', 'piano', 'OPTIMAL'),
        ('Santo Mejía', 'Alejandro Mejía', 'voz_femenina', 'OPTIMAL'),
        ('¡Oh Cordero de Dios!', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('¡Oh Cordero de Dios!', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('¡Oh Cordero de Dios!', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('¡Oh Cordero de Dios!', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Cordero Mejía', 'Alejandro Mejía', 'piano', 'MINIMUM'),
        ('Cordero Mejía', 'Alejandro Mejía', 'voz_femenina', 'MINIMUM'),
        ('Cordero Mejía', 'Alejandro Mejía', 'piano', 'OPTIMAL'),
        ('Cordero Mejía', 'Alejandro Mejía', 'voz_femenina', 'OPTIMAL'),
        ('Cordero (Comunidad Sta. María)', 'Comunidad Sta. María', 'piano', 'MINIMUM'),
        ('Cordero (Comunidad Sta. María)', 'Comunidad Sta. María', 'voz_femenina', 'MINIMUM'),
        ('Cordero (Comunidad Sta. María)', 'Comunidad Sta. María', 'piano', 'OPTIMAL'),
        ('Cordero (Comunidad Sta. María)', 'Comunidad Sta. María', 'voz_femenina', 'OPTIMAL'),
        ('Cordero Dynamis', 'Dynamis', 'piano', 'MINIMUM'),
        ('Cordero Dynamis', 'Dynamis', 'voz_femenina', 'MINIMUM'),
        ('Cordero Dynamis', 'Dynamis', 'piano', 'OPTIMAL'),
        ('Cordero Dynamis', 'Dynamis', 'voz_femenina', 'OPTIMAL'),
        ('Cordero 2020', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cordero 2020', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cordero 2020', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cordero 2020', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Divino Manjar', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Divino Manjar', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Divino Manjar', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Divino Manjar', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'piano', 'MINIMUM'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'voz_femenina', 'MINIMUM'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'piano', 'OPTIMAL'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'voz_femenina', 'OPTIMAL'),
        ('Pescador de hombres', 'Cesáreo Gabaráin', 'violin_1', 'OPTIMAL'),
        ('El amor de mi Dios', 'Hna. Inés de Jesús', 'piano', 'MINIMUM'),
        ('El amor de mi Dios', 'Hna. Inés de Jesús', 'voz_femenina', 'MINIMUM'),
        ('El amor de mi Dios', 'Hna. Inés de Jesús', 'piano', 'OPTIMAL'),
        ('El amor de mi Dios', 'Hna. Inés de Jesús', 'voz_femenina', 'OPTIMAL'),
        ('Por Amor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Por Amor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Por Amor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Por Amor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('¡Oh Buen Jesús!', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('¡Oh Buen Jesús!', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('¡Oh Buen Jesús!', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('¡Oh Buen Jesús!', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Pan de vida, pan de fe', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Pan de vida, pan de fe', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Pan de vida, pan de fe', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Pan de vida, pan de fe', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Milagro de Amor', 'Tradicional litúrgico', 'violin_1', 'OPTIMAL'),
        ('Me has seducido, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Me has seducido, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Me has seducido, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Me has seducido, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Verbum Panis', 'Verbum Panis', 'piano', 'MINIMUM'),
        ('Verbum Panis', 'Verbum Panis', 'voz_femenina', 'MINIMUM'),
        ('Verbum Panis', 'Verbum Panis', 'piano', 'OPTIMAL'),
        ('Verbum Panis', 'Verbum Panis', 'voz_femenina', 'OPTIMAL'),
        ('Alma de Cristo', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Alma de Cristo', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Alma de Cristo', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Alma de Cristo', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Ya no eres pan y vino', 'Jorge Luis Bohórquez', 'piano', 'MINIMUM'),
        ('Ya no eres pan y vino', 'Jorge Luis Bohórquez', 'voz_femenina', 'MINIMUM'),
        ('Ya no eres pan y vino', 'Jorge Luis Bohórquez', 'piano', 'OPTIMAL'),
        ('Ya no eres pan y vino', 'Jorge Luis Bohórquez', 'voz_femenina', 'OPTIMAL'),
        ('Ave María Solidaria', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Ave María Solidaria', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Ave María Solidaria', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Ave María Solidaria', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Alianza de Amor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Tus Maravillas', 'Verbum Panis', 'piano', 'MINIMUM'),
        ('Tus Maravillas', 'Verbum Panis', 'voz_femenina', 'MINIMUM'),
        ('Tus Maravillas', 'Verbum Panis', 'piano', 'OPTIMAL'),
        ('Tus Maravillas', 'Verbum Panis', 'voz_femenina', 'OPTIMAL'),
        ('Ave María', 'Franz Schubert', 'piano', 'MINIMUM'),
        ('Ave María', 'Franz Schubert', 'voz_femenina', 'MINIMUM'),
        ('Ave María', 'Franz Schubert', 'piano', 'OPTIMAL'),
        ('Ave María', 'Franz Schubert', 'voz_femenina', 'OPTIMAL'),
        ('Ave María', 'Franz Schubert', 'violin_1', 'OPTIMAL'),
        ('Ave María', 'Franz Schubert', 'cello', 'OPTIMAL'),
        ('Ave María', 'Verbum Panis', 'piano', 'MINIMUM'),
        ('Ave María', 'Verbum Panis', 'voz_femenina', 'MINIMUM'),
        ('Ave María', 'Verbum Panis', 'piano', 'OPTIMAL'),
        ('Ave María', 'Verbum Panis', 'voz_femenina', 'OPTIMAL'),
        ('Ave María', 'Verbum Panis', 'violin_1', 'OPTIMAL'),
        ('Juramento', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Juramento', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Juramento', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Juramento', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Hoy he vuelto', 'Cesáreo Gabaráin', 'piano', 'MINIMUM'),
        ('Hoy he vuelto', 'Cesáreo Gabaráin', 'voz_femenina', 'MINIMUM'),
        ('Hoy he vuelto', 'Cesáreo Gabaráin', 'piano', 'OPTIMAL'),
        ('Hoy he vuelto', 'Cesáreo Gabaráin', 'voz_femenina', 'OPTIMAL'),
        ('No voy a decirte adiós', 'Alfareros', 'piano', 'MINIMUM'),
        ('No voy a decirte adiós', 'Alfareros', 'voz_femenina', 'MINIMUM'),
        ('No voy a decirte adiós', 'Alfareros', 'piano', 'OPTIMAL'),
        ('No voy a decirte adiós', 'Alfareros', 'voz_femenina', 'OPTIMAL'),
        ('Toda Hermosa', 'Hna. Inés de Jesús', 'piano', 'MINIMUM'),
        ('Toda Hermosa', 'Hna. Inés de Jesús', 'voz_femenina', 'MINIMUM'),
        ('Toda Hermosa', 'Hna. Inés de Jesús', 'piano', 'OPTIMAL'),
        ('Toda Hermosa', 'Hna. Inés de Jesús', 'voz_femenina', 'OPTIMAL'),
        ('Toma mi mano', 'Alfareros', 'piano', 'MINIMUM'),
        ('Toma mi mano', 'Alfareros', 'voz_femenina', 'MINIMUM'),
        ('Toma mi mano', 'Alfareros', 'piano', 'OPTIMAL'),
        ('Toma mi mano', 'Alfareros', 'voz_femenina', 'OPTIMAL'),
        ('Rezo por ti', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Rezo por ti', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Rezo por ti', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Rezo por ti', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Madre del Silencio', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Madre del Silencio', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Madre del Silencio', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Madre del Silencio', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('María Tú', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('María Tú', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('María Tú', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('María Tú', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('De aquí hasta el final', 'Tradicional', 'piano', 'MINIMUM'),
        ('De aquí hasta el final', 'Tradicional', 'voz_femenina', 'MINIMUM'),
        ('De aquí hasta el final', 'Tradicional', 'piano', 'OPTIMAL'),
        ('De aquí hasta el final', 'Tradicional', 'voz_femenina', 'OPTIMAL'),
        ('Marcha Nupcial Wagner', 'Richard Wagner', 'piano', 'MINIMUM'),
        ('Marcha Nupcial Wagner', 'Richard Wagner', 'piano', 'OPTIMAL'),
        ('Marcha Nupcial Wagner', 'Richard Wagner', 'violin_1', 'OPTIMAL'),
        ('Marcha Nupcial Wagner', 'Richard Wagner', 'violin_2', 'OPTIMAL'),
        ('Perfect', 'Ed Sheeran', 'piano', 'MINIMUM'),
        ('Perfect', 'Ed Sheeran', 'voz_femenina', 'MINIMUM'),
        ('Perfect', 'Ed Sheeran', 'piano', 'OPTIMAL'),
        ('Perfect', 'Ed Sheeran', 'voz_femenina', 'OPTIMAL'),
        ('Perfect', 'Ed Sheeran', 'violin_1', 'OPTIMAL'),
        ('Perfect', 'Ed Sheeran', 'cello', 'OPTIMAL'),
        ('A Thousand Years', 'Christina Perri', 'piano', 'MINIMUM'),
        ('A Thousand Years', 'Christina Perri', 'voz_femenina', 'MINIMUM'),
        ('A Thousand Years', 'Christina Perri', 'piano', 'OPTIMAL'),
        ('A Thousand Years', 'Christina Perri', 'voz_femenina', 'OPTIMAL'),
        ('A Thousand Years', 'Christina Perri', 'violin_1', 'OPTIMAL'),
        ('Thinking Out Loud', 'Ed Sheeran', 'piano', 'MINIMUM'),
        ('Thinking Out Loud', 'Ed Sheeran', 'voz_femenina', 'MINIMUM'),
        ('Thinking Out Loud', 'Ed Sheeran', 'piano', 'OPTIMAL'),
        ('Thinking Out Loud', 'Ed Sheeran', 'voz_femenina', 'OPTIMAL'),
        ('Thinking Out Loud', 'Ed Sheeran', 'violin_1', 'OPTIMAL'),
        ('All of Me', 'John Legend', 'piano', 'MINIMUM'),
        ('All of Me', 'John Legend', 'voz_femenina', 'MINIMUM'),
        ('All of Me', 'John Legend', 'piano', 'OPTIMAL'),
        ('All of Me', 'John Legend', 'voz_femenina', 'OPTIMAL'),
        ('All of Me', 'John Legend', 'violin_1', 'OPTIMAL'),
        ('All of Me', 'John Legend', 'cello', 'OPTIMAL'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'piano', 'MINIMUM'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'voz_femenina', 'MINIMUM'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'piano', 'OPTIMAL'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'voz_femenina', 'OPTIMAL'),
        ('Can''t Help Falling in Love', 'Elvis Presley', 'violin_1', 'OPTIMAL'),
        ('Marry You', 'Bruno Mars', 'piano', 'MINIMUM'),
        ('Marry You', 'Bruno Mars', 'voz_femenina', 'MINIMUM'),
        ('Marry You', 'Bruno Mars', 'piano', 'OPTIMAL'),
        ('Marry You', 'Bruno Mars', 'voz_femenina', 'OPTIMAL'),
        ('You Raise Me Up', 'Josh Groban', 'piano', 'MINIMUM'),
        ('You Raise Me Up', 'Josh Groban', 'voz_femenina', 'MINIMUM'),
        ('You Raise Me Up', 'Josh Groban', 'piano', 'OPTIMAL'),
        ('You Raise Me Up', 'Josh Groban', 'voz_femenina', 'OPTIMAL'),
        ('You Raise Me Up', 'Josh Groban', 'violin_1', 'OPTIMAL'),
        ('You Raise Me Up', 'Josh Groban', 'cello', 'OPTIMAL'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'piano', 'MINIMUM'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'voz_femenina', 'MINIMUM'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'piano', 'OPTIMAL'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'voz_femenina', 'OPTIMAL'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'violin_1', 'OPTIMAL'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'cello', 'OPTIMAL'),
        ('Stand by Me', 'Ben E. King', 'piano', 'MINIMUM'),
        ('Stand by Me', 'Ben E. King', 'voz_femenina', 'MINIMUM'),
        ('Stand by Me', 'Ben E. King', 'piano', 'OPTIMAL'),
        ('Stand by Me', 'Ben E. King', 'voz_femenina', 'OPTIMAL'),
        ('Treasure', 'Bruno Mars', 'piano', 'MINIMUM'),
        ('Treasure', 'Bruno Mars', 'voz_femenina', 'MINIMUM'),
        ('Treasure', 'Bruno Mars', 'piano', 'OPTIMAL'),
        ('Treasure', 'Bruno Mars', 'voz_femenina', 'OPTIMAL'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'piano', 'MINIMUM'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'voz_femenina', 'MINIMUM'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'piano', 'OPTIMAL'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'voz_femenina', 'OPTIMAL'),
        ('Just the Two of Us', 'Grover Washington Jr. & Bill Withers', 'saxo_soprano', 'OPTIMAL'),
        ('Kiss Me', 'Sixpence None the Richer', 'piano', 'MINIMUM'),
        ('Kiss Me', 'Sixpence None the Richer', 'voz_femenina', 'MINIMUM'),
        ('Kiss Me', 'Sixpence None the Richer', 'piano', 'OPTIMAL'),
        ('Kiss Me', 'Sixpence None the Richer', 'voz_femenina', 'OPTIMAL'),
        ('Best Day of My Life', 'American Authors', 'piano', 'MINIMUM'),
        ('Best Day of My Life', 'American Authors', 'voz_femenina', 'MINIMUM'),
        ('Best Day of My Life', 'American Authors', 'piano', 'OPTIMAL'),
        ('Best Day of My Life', 'American Authors', 'voz_femenina', 'OPTIMAL'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'piano', 'MINIMUM'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'voz_femenina', 'MINIMUM'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'piano', 'OPTIMAL'),
        ('Could I Love You Any More', 'Jason Mraz & Reneé Dominique', 'voz_femenina', 'OPTIMAL'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'piano', 'MINIMUM'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'voz_femenina', 'MINIMUM'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'piano', 'OPTIMAL'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'voz_femenina', 'OPTIMAL'),
        ('Isn''t She Lovely', 'Stevie Wonder', 'saxo_soprano', 'OPTIMAL'),
        ('Sunday Morning', 'Maroon 5', 'piano', 'MINIMUM'),
        ('Sunday Morning', 'Maroon 5', 'voz_femenina', 'MINIMUM'),
        ('Sunday Morning', 'Maroon 5', 'piano', 'OPTIMAL'),
        ('Sunday Morning', 'Maroon 5', 'voz_femenina', 'OPTIMAL'),
        ('Sugar', 'Maroon 5', 'piano', 'MINIMUM'),
        ('Sugar', 'Maroon 5', 'voz_femenina', 'MINIMUM'),
        ('Sugar', 'Maroon 5', 'piano', 'OPTIMAL'),
        ('Sugar', 'Maroon 5', 'voz_femenina', 'OPTIMAL'),
        ('Game of Love', 'Wayne Fontana', 'piano', 'MINIMUM'),
        ('Game of Love', 'Wayne Fontana', 'voz_femenina', 'MINIMUM'),
        ('Game of Love', 'Wayne Fontana', 'piano', 'OPTIMAL'),
        ('Game of Love', 'Wayne Fontana', 'voz_femenina', 'OPTIMAL'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'piano', 'MINIMUM'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'voz_femenina', 'MINIMUM'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'piano', 'OPTIMAL'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'voz_femenina', 'OPTIMAL'),
        ('I Don''t Want to Miss a Thing', 'Aerosmith', 'violin_1', 'OPTIMAL'),
        ('At Last', 'Etta James', 'piano', 'MINIMUM'),
        ('At Last', 'Etta James', 'voz_femenina', 'MINIMUM'),
        ('At Last', 'Etta James', 'piano', 'OPTIMAL'),
        ('At Last', 'Etta James', 'voz_femenina', 'OPTIMAL'),
        ('At Last', 'Etta James', 'saxo_soprano', 'OPTIMAL'),
        ('Wonderful Tonight', 'Eric Clapton', 'piano', 'MINIMUM'),
        ('Wonderful Tonight', 'Eric Clapton', 'voz_femenina', 'MINIMUM'),
        ('Wonderful Tonight', 'Eric Clapton', 'piano', 'OPTIMAL'),
        ('Wonderful Tonight', 'Eric Clapton', 'voz_femenina', 'OPTIMAL'),
        ('Your Song', 'Elton John', 'piano', 'MINIMUM'),
        ('Your Song', 'Elton John', 'voz_femenina', 'MINIMUM'),
        ('Your Song', 'Elton John', 'piano', 'OPTIMAL'),
        ('Your Song', 'Elton John', 'voz_femenina', 'OPTIMAL'),
        ('Make You Feel My Love', 'Adele', 'piano', 'MINIMUM'),
        ('Make You Feel My Love', 'Adele', 'voz_femenina', 'MINIMUM'),
        ('Make You Feel My Love', 'Adele', 'piano', 'OPTIMAL'),
        ('Make You Feel My Love', 'Adele', 'voz_femenina', 'OPTIMAL'),
        ('I Loved Her First', 'Heartland', 'piano', 'MINIMUM'),
        ('I Loved Her First', 'Heartland', 'voz_femenina', 'MINIMUM'),
        ('I Loved Her First', 'Heartland', 'piano', 'OPTIMAL'),
        ('I Loved Her First', 'Heartland', 'voz_femenina', 'OPTIMAL'),
        ('I Loved Her First', 'Heartland', 'violin_1', 'OPTIMAL'),
        ('From This Moment On', 'Shania Twain', 'piano', 'MINIMUM'),
        ('From This Moment On', 'Shania Twain', 'voz_femenina', 'MINIMUM'),
        ('From This Moment On', 'Shania Twain', 'piano', 'OPTIMAL'),
        ('From This Moment On', 'Shania Twain', 'voz_femenina', 'OPTIMAL'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'piano', 'MINIMUM'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'voz_femenina', 'MINIMUM'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'piano', 'OPTIMAL'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'voz_femenina', 'OPTIMAL'),
        ('The Way You Look Tonight', 'Frank Sinatra', 'saxo_soprano', 'OPTIMAL')

    INSERT INTO @reqs(titulo, autor, slug_inst, tipo) VALUES
        ('Everything', 'Michael Bublé', 'piano', 'MINIMUM'),
        ('Everything', 'Michael Bublé', 'voz_femenina', 'MINIMUM'),
        ('Everything', 'Michael Bublé', 'piano', 'OPTIMAL'),
        ('Everything', 'Michael Bublé', 'voz_femenina', 'OPTIMAL'),
        ('I''m Yours', 'Jason Mraz', 'piano', 'MINIMUM'),
        ('I''m Yours', 'Jason Mraz', 'voz_femenina', 'MINIMUM'),
        ('I''m Yours', 'Jason Mraz', 'piano', 'OPTIMAL'),
        ('I''m Yours', 'Jason Mraz', 'voz_femenina', 'OPTIMAL'),
        ('Better Together', 'Jack Johnson', 'piano', 'MINIMUM'),
        ('Better Together', 'Jack Johnson', 'voz_femenina', 'MINIMUM'),
        ('Better Together', 'Jack Johnson', 'piano', 'OPTIMAL'),
        ('Better Together', 'Jack Johnson', 'voz_femenina', 'OPTIMAL'),
        ('Say You Won''t Let Go', 'James Arthur', 'piano', 'MINIMUM'),
        ('Say You Won''t Let Go', 'James Arthur', 'voz_femenina', 'MINIMUM'),
        ('Say You Won''t Let Go', 'James Arthur', 'piano', 'OPTIMAL'),
        ('Say You Won''t Let Go', 'James Arthur', 'voz_femenina', 'OPTIMAL'),
        ('Say You Won''t Let Go', 'James Arthur', 'violin_1', 'OPTIMAL'),
        ('My Girl', 'The Temptations', 'piano', 'MINIMUM'),
        ('My Girl', 'The Temptations', 'voz_femenina', 'MINIMUM'),
        ('My Girl', 'The Temptations', 'piano', 'OPTIMAL'),
        ('My Girl', 'The Temptations', 'voz_femenina', 'OPTIMAL'),
        ('La Vie en Rose', 'Édith Piaf', 'piano', 'MINIMUM'),
        ('La Vie en Rose', 'Édith Piaf', 'voz_femenina', 'MINIMUM'),
        ('La Vie en Rose', 'Édith Piaf', 'piano', 'OPTIMAL'),
        ('La Vie en Rose', 'Édith Piaf', 'voz_femenina', 'OPTIMAL'),
        ('La Vie en Rose', 'Édith Piaf', 'violin_1', 'OPTIMAL'),
        ('Unchained Melody', 'The Righteous Brothers', 'piano', 'MINIMUM'),
        ('Unchained Melody', 'The Righteous Brothers', 'voz_femenina', 'MINIMUM'),
        ('Unchained Melody', 'The Righteous Brothers', 'piano', 'OPTIMAL'),
        ('Unchained Melody', 'The Righteous Brothers', 'voz_femenina', 'OPTIMAL'),
        ('Have I Told You Lately', 'Van Morrison', 'piano', 'MINIMUM'),
        ('Have I Told You Lately', 'Van Morrison', 'voz_femenina', 'MINIMUM'),
        ('Have I Told You Lately', 'Van Morrison', 'piano', 'OPTIMAL'),
        ('Have I Told You Lately', 'Van Morrison', 'voz_femenina', 'OPTIMAL'),
        ('When You Say Nothing at All', 'Ronan Keating', 'piano', 'MINIMUM'),
        ('When You Say Nothing at All', 'Ronan Keating', 'voz_femenina', 'MINIMUM'),
        ('When You Say Nothing at All', 'Ronan Keating', 'piano', 'OPTIMAL'),
        ('When You Say Nothing at All', 'Ronan Keating', 'voz_femenina', 'OPTIMAL'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'piano', 'MINIMUM'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'voz_femenina', 'MINIMUM'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'piano', 'OPTIMAL'),
        ('Si nos dejan', 'José Alfredo Jiménez', 'voz_femenina', 'OPTIMAL'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'piano', 'MINIMUM'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'voz_femenina', 'MINIMUM'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'piano', 'OPTIMAL'),
        ('Un Mundo Ideal', 'Aladdin — Disney', 'voz_femenina', 'OPTIMAL'),
        ('Hasta mi final', 'Il Divo', 'piano', 'MINIMUM'),
        ('Hasta mi final', 'Il Divo', 'voz_femenina', 'MINIMUM'),
        ('Hasta mi final', 'Il Divo', 'piano', 'OPTIMAL'),
        ('Hasta mi final', 'Il Divo', 'voz_femenina', 'OPTIMAL'),
        ('Hasta mi final', 'Il Divo', 'violin_1', 'OPTIMAL'),
        ('Hasta mi final', 'Il Divo', 'cello', 'OPTIMAL'),
        ('Un mismo corazón', 'Tradicional', 'piano', 'MINIMUM'),
        ('Un mismo corazón', 'Tradicional', 'voz_femenina', 'MINIMUM'),
        ('Un mismo corazón', 'Tradicional', 'piano', 'OPTIMAL'),
        ('Un mismo corazón', 'Tradicional', 'voz_femenina', 'OPTIMAL'),
        ('Amor Eterno', 'Juan Gabriel', 'piano', 'MINIMUM'),
        ('Amor Eterno', 'Juan Gabriel', 'voz_femenina', 'MINIMUM'),
        ('Amor Eterno', 'Juan Gabriel', 'piano', 'OPTIMAL'),
        ('Amor Eterno', 'Juan Gabriel', 'voz_femenina', 'OPTIMAL'),
        ('Amor Eterno', 'Juan Gabriel', 'violin_1', 'OPTIMAL'),
        ('Una madre no se cansa de olvidar', 'Tradicional', 'piano', 'MINIMUM'),
        ('Una madre no se cansa de olvidar', 'Tradicional', 'voz_femenina', 'MINIMUM'),
        ('Una madre no se cansa de olvidar', 'Tradicional', 'piano', 'OPTIMAL'),
        ('Una madre no se cansa de olvidar', 'Tradicional', 'voz_femenina', 'OPTIMAL'),
        ('Te diré que sí', 'Edith Aravena', 'piano', 'MINIMUM'),
        ('Te diré que sí', 'Edith Aravena', 'voz_femenina', 'MINIMUM'),
        ('Te diré que sí', 'Edith Aravena', 'piano', 'OPTIMAL'),
        ('Te diré que sí', 'Edith Aravena', 'voz_femenina', 'OPTIMAL'),
        ('Cuando llego a casa', 'Fonseca', 'piano', 'MINIMUM'),
        ('Cuando llego a casa', 'Fonseca', 'voz_femenina', 'MINIMUM'),
        ('Cuando llego a casa', 'Fonseca', 'piano', 'OPTIMAL'),
        ('Cuando llego a casa', 'Fonseca', 'voz_femenina', 'OPTIMAL'),
        ('Regalo del Cielo', 'Athenas', 'piano', 'MINIMUM'),
        ('Regalo del Cielo', 'Athenas', 'voz_femenina', 'MINIMUM'),
        ('Regalo del Cielo', 'Athenas', 'piano', 'OPTIMAL'),
        ('Regalo del Cielo', 'Athenas', 'voz_femenina', 'OPTIMAL'),
        ('Por ti seré', 'Il Divo', 'piano', 'MINIMUM'),
        ('Por ti seré', 'Il Divo', 'voz_femenina', 'MINIMUM'),
        ('Por ti seré', 'Il Divo', 'piano', 'OPTIMAL'),
        ('Por ti seré', 'Il Divo', 'voz_femenina', 'OPTIMAL'),
        ('Por ti seré', 'Il Divo', 'violin_1', 'OPTIMAL'),
        ('Por ti seré', 'Il Divo', 'cello', 'OPTIMAL'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'piano', 'MINIMUM'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'voz_femenina', 'MINIMUM'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'piano', 'OPTIMAL'),
        ('Por el resto de mi vida', 'Andrés Cepeda', 'voz_femenina', 'OPTIMAL'),
        ('Contigo aprendí', 'Armando Manzanero', 'piano', 'MINIMUM'),
        ('Contigo aprendí', 'Armando Manzanero', 'voz_femenina', 'MINIMUM'),
        ('Contigo aprendí', 'Armando Manzanero', 'piano', 'OPTIMAL'),
        ('Contigo aprendí', 'Armando Manzanero', 'voz_femenina', 'OPTIMAL'),
        ('Hoy tengo ganas de ti', 'Alejandro Fernández', 'piano', 'MINIMUM'),
        ('Hoy tengo ganas de ti', 'Alejandro Fernández', 'voz_femenina', 'MINIMUM'),
        ('Hoy tengo ganas de ti', 'Alejandro Fernández', 'piano', 'OPTIMAL'),
        ('Hoy tengo ganas de ti', 'Alejandro Fernández', 'voz_femenina', 'OPTIMAL'),
        ('Tu poeta', 'Alex Campos', 'piano', 'MINIMUM'),
        ('Tu poeta', 'Alex Campos', 'voz_femenina', 'MINIMUM'),
        ('Tu poeta', 'Alex Campos', 'piano', 'OPTIMAL'),
        ('Tu poeta', 'Alex Campos', 'voz_femenina', 'OPTIMAL'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'piano', 'MINIMUM'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'voz_femenina', 'MINIMUM'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'piano', 'OPTIMAL'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'voz_femenina', 'OPTIMAL'),
        ('Nuestra Historia', 'JAEL & Caro Ramírez', 'violin_1', 'OPTIMAL'),
        ('Estoy hecho de pedacitos de ti', 'Antonio Orozco', 'piano', 'MINIMUM'),
        ('Estoy hecho de pedacitos de ti', 'Antonio Orozco', 'voz_femenina', 'MINIMUM'),
        ('Estoy hecho de pedacitos de ti', 'Antonio Orozco', 'piano', 'OPTIMAL'),
        ('Estoy hecho de pedacitos de ti', 'Antonio Orozco', 'voz_femenina', 'OPTIMAL'),
        ('Solamente tú', 'Pablo Alborán', 'piano', 'MINIMUM'),
        ('Solamente tú', 'Pablo Alborán', 'voz_femenina', 'MINIMUM'),
        ('Solamente tú', 'Pablo Alborán', 'piano', 'OPTIMAL'),
        ('Solamente tú', 'Pablo Alborán', 'voz_femenina', 'OPTIMAL'),
        ('Cómo te extraño', 'Leo Dan', 'piano', 'MINIMUM'),
        ('Cómo te extraño', 'Leo Dan', 'voz_femenina', 'MINIMUM'),
        ('Cómo te extraño', 'Leo Dan', 'piano', 'OPTIMAL'),
        ('Cómo te extraño', 'Leo Dan', 'voz_femenina', 'OPTIMAL'),
        ('Por ti volaré', 'Andrea Bocelli', 'piano', 'MINIMUM'),
        ('Por ti volaré', 'Andrea Bocelli', 'voz_femenina', 'MINIMUM'),
        ('Por ti volaré', 'Andrea Bocelli', 'piano', 'OPTIMAL'),
        ('Por ti volaré', 'Andrea Bocelli', 'voz_femenina', 'OPTIMAL'),
        ('Por ti volaré', 'Andrea Bocelli', 'violin_1', 'OPTIMAL'),
        ('Por ti volaré', 'Andrea Bocelli', 'cello', 'OPTIMAL'),
        ('Bésame mucho', 'Consuelo Velázquez', 'piano', 'MINIMUM'),
        ('Bésame mucho', 'Consuelo Velázquez', 'voz_femenina', 'MINIMUM'),
        ('Bésame mucho', 'Consuelo Velázquez', 'piano', 'OPTIMAL'),
        ('Bésame mucho', 'Consuelo Velázquez', 'voz_femenina', 'OPTIMAL'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'piano', 'MINIMUM'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'voz_femenina', 'MINIMUM'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'piano', 'OPTIMAL'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'voz_femenina', 'OPTIMAL'),
        ('Quizás, quizás, quizás', 'Osvaldo Farrés', 'saxo_soprano', 'OPTIMAL'),
        ('Sabor a mí', 'Álvaro Carrillo', 'piano', 'MINIMUM'),
        ('Sabor a mí', 'Álvaro Carrillo', 'voz_femenina', 'MINIMUM'),
        ('Sabor a mí', 'Álvaro Carrillo', 'piano', 'OPTIMAL'),
        ('Sabor a mí', 'Álvaro Carrillo', 'voz_femenina', 'OPTIMAL'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'piano', 'MINIMUM'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'voz_femenina', 'MINIMUM'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'piano', 'OPTIMAL'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'voz_femenina', 'OPTIMAL'),
        ('Historia de un amor', 'Carlos Eleta Almarán', 'violin_1', 'OPTIMAL'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'piano', 'MINIMUM'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'violin_1', 'MINIMUM'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'violin_2', 'MINIMUM'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'piano', 'OPTIMAL'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'violin_1', 'OPTIMAL'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'violin_2', 'OPTIMAL'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'cello', 'OPTIMAL'),
        ('La Rejouissance', 'G.F. Haendel', 'piano', 'MINIMUM'),
        ('La Rejouissance', 'G.F. Haendel', 'violin_1', 'MINIMUM'),
        ('La Rejouissance', 'G.F. Haendel', 'piano', 'OPTIMAL'),
        ('La Rejouissance', 'G.F. Haendel', 'violin_1', 'OPTIMAL'),
        ('La Rejouissance', 'G.F. Haendel', 'violin_2', 'OPTIMAL'),
        ('Trumpet Tune', 'Henry Purcell', 'piano', 'MINIMUM'),
        ('Trumpet Tune', 'Henry Purcell', 'piano', 'OPTIMAL'),
        ('Trumpet Tune', 'Henry Purcell', 'violin_1', 'OPTIMAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'piano', 'MINIMUM'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'piano', 'OPTIMAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'violin_1', 'OPTIMAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'violin_2', 'OPTIMAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'cello', 'OPTIMAL'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'piano', 'MINIMUM'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'violin_1', 'MINIMUM'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'piano', 'OPTIMAL'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'violin_1', 'OPTIMAL'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'violin_2', 'OPTIMAL'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'cello', 'OPTIMAL'),
        ('Minueto en Sol', 'Luigi Boccherini', 'piano', 'MINIMUM'),
        ('Minueto en Sol', 'Luigi Boccherini', 'violin_1', 'MINIMUM'),
        ('Minueto en Sol', 'Luigi Boccherini', 'piano', 'OPTIMAL'),
        ('Minueto en Sol', 'Luigi Boccherini', 'violin_1', 'OPTIMAL'),
        ('Minueto en Sol', 'Luigi Boccherini', 'violin_2', 'OPTIMAL'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'piano', 'MINIMUM'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'voz_femenina', 'MINIMUM'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'piano', 'OPTIMAL'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'voz_femenina', 'OPTIMAL'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'violin_1', 'OPTIMAL'),
        ('Delante del altar', 'Joel Cruz', 'piano', 'MINIMUM'),
        ('Delante del altar', 'Joel Cruz', 'voz_femenina', 'MINIMUM'),
        ('Delante del altar', 'Joel Cruz', 'piano', 'OPTIMAL'),
        ('Delante del altar', 'Joel Cruz', 'voz_femenina', 'OPTIMAL'),
        ('Delante del altar', 'Joel Cruz', 'violin_1', 'OPTIMAL'),
        ('Aclaró', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Aclaró', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Aclaró', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Aclaró', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'piano', 'MINIMUM'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'voz_femenina', 'MINIMUM'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'piano', 'OPTIMAL'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'voz_femenina', 'OPTIMAL'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'violin_1', 'OPTIMAL'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'cello', 'OPTIMAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'piano', 'MINIMUM'),
        ('O mio babbino caro', 'Giacomo Puccini', 'voz_femenina', 'MINIMUM'),
        ('O mio babbino caro', 'Giacomo Puccini', 'piano', 'OPTIMAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'voz_femenina', 'OPTIMAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'violin_1', 'OPTIMAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'cello', 'OPTIMAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'piano', 'MINIMUM'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'voz_femenina', 'MINIMUM'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'piano', 'OPTIMAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'voz_femenina', 'OPTIMAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'violin_1', 'OPTIMAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'cello', 'OPTIMAL'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'piano', 'MINIMUM'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'voz_femenina', 'MINIMUM'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'piano', 'OPTIMAL'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'voz_femenina', 'OPTIMAL'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'violin_1', 'OPTIMAL'),
        ('Meditación de Thaïs', 'Jules Massenet', 'piano', 'MINIMUM'),
        ('Meditación de Thaïs', 'Jules Massenet', 'violin_1', 'MINIMUM'),
        ('Meditación de Thaïs', 'Jules Massenet', 'piano', 'OPTIMAL'),
        ('Meditación de Thaïs', 'Jules Massenet', 'violin_1', 'OPTIMAL'),
        ('Meditación de Thaïs', 'Jules Massenet', 'violin_2', 'OPTIMAL'),
        ('Meditación de Thaïs', 'Jules Massenet', 'cello', 'OPTIMAL'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'piano', 'MINIMUM'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'violin_1', 'MINIMUM'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'piano', 'OPTIMAL'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'violin_1', 'OPTIMAL'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'violin_2', 'OPTIMAL'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'cello', 'OPTIMAL'),
        ('Rivers Flows in You', 'Yiruma', 'piano', 'MINIMUM'),
        ('Rivers Flows in You', 'Yiruma', 'piano', 'OPTIMAL'),
        ('Rivers Flows in You', 'Yiruma', 'violin_1', 'OPTIMAL'),
        ('Only Time', 'Enya', 'piano', 'MINIMUM'),
        ('Only Time', 'Enya', 'voz_femenina', 'MINIMUM'),
        ('Only Time', 'Enya', 'piano', 'OPTIMAL'),
        ('Only Time', 'Enya', 'voz_femenina', 'OPTIMAL'),
        ('Ven amada mía', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Ven amada mía', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Ven amada mía', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Ven amada mía', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Ven amada mía', 'Tradicional litúrgico', 'violin_1', 'OPTIMAL'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'piano', 'MINIMUM'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'voz_femenina', 'MINIMUM'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'piano', 'OPTIMAL'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'voz_femenina', 'OPTIMAL'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'violin_1', 'OPTIMAL'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'piano', 'MINIMUM'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'MINIMUM'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'piano', 'OPTIMAL'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'OPTIMAL'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'piano', 'MINIMUM'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'voz_femenina', 'MINIMUM'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'piano', 'OPTIMAL'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'voz_femenina', 'OPTIMAL'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'piano', 'MINIMUM'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'voz_femenina', 'MINIMUM'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'piano', 'OPTIMAL'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'voz_femenina', 'OPTIMAL'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'violin_1', 'OPTIMAL'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'piano', 'MINIMUM'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'voz_femenina', 'MINIMUM'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'piano', 'OPTIMAL'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'voz_femenina', 'OPTIMAL'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'piano', 'MINIMUM'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'voz_femenina', 'MINIMUM'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'piano', 'OPTIMAL'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'voz_femenina', 'OPTIMAL'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'violin_1', 'OPTIMAL'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'violin_2', 'OPTIMAL'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'piano', 'MINIMUM'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'voz_femenina', 'MINIMUM'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'piano', 'OPTIMAL'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'voz_femenina', 'OPTIMAL'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Dios está aquí', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Dios está aquí', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Dios está aquí', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Dios está aquí', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'piano', 'MINIMUM'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'voz_femenina', 'MINIMUM'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'piano', 'OPTIMAL'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'voz_femenina', 'OPTIMAL'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Oración por la Familia', 'Padre Zezinho', 'piano', 'MINIMUM'),
        ('Oración por la Familia', 'Padre Zezinho', 'voz_femenina', 'MINIMUM'),
        ('Oración por la Familia', 'Padre Zezinho', 'piano', 'OPTIMAL'),
        ('Oración por la Familia', 'Padre Zezinho', 'voz_femenina', 'OPTIMAL'),
        ('Oración por la Familia', 'Padre Zezinho', 'violin_1', 'OPTIMAL'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Ante tu altar', 'Walmir Alencar', 'piano', 'MINIMUM'),
        ('Ante tu altar', 'Walmir Alencar', 'voz_femenina', 'MINIMUM'),
        ('Ante tu altar', 'Walmir Alencar', 'piano', 'OPTIMAL'),
        ('Ante tu altar', 'Walmir Alencar', 'voz_femenina', 'OPTIMAL'),
        ('Ante tu altar', 'Walmir Alencar', 'violin_1', 'OPTIMAL'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Cinco panes', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Cinco panes', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Cinco panes', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Cinco panes', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'piano', 'MINIMUM'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'voz_femenina', 'MINIMUM'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'piano', 'OPTIMAL'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'voz_femenina', 'OPTIMAL'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'violin_1', 'OPTIMAL'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'cello', 'OPTIMAL'),
        ('Tómame', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Tómame', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Tómame', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Tómame', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'piano', 'MINIMUM'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'voz_femenina', 'MINIMUM'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'piano', 'OPTIMAL'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'voz_femenina', 'OPTIMAL'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'violin_1', 'OPTIMAL'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'cello', 'OPTIMAL'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'piano', 'MINIMUM'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'voz_femenina', 'MINIMUM'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'piano', 'OPTIMAL'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'voz_femenina', 'OPTIMAL'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'violin_1', 'OPTIMAL'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'piano', 'MINIMUM'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'MINIMUM'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'piano', 'OPTIMAL'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'OPTIMAL'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'piano', 'MINIMUM'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'voz_femenina', 'MINIMUM'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'piano', 'OPTIMAL'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'voz_femenina', 'OPTIMAL'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'violin_1', 'OPTIMAL'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'piano', 'MINIMUM'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'MINIMUM'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'piano', 'OPTIMAL'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'voz_femenina', 'OPTIMAL'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'piano', 'MINIMUM'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'voz_femenina', 'MINIMUM'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'piano', 'OPTIMAL'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'voz_femenina', 'OPTIMAL'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'violin_1', 'OPTIMAL'),
        ('Un pacto con Dios', 'Rabito', 'piano', 'MINIMUM'),
        ('Un pacto con Dios', 'Rabito', 'voz_femenina', 'MINIMUM'),
        ('Un pacto con Dios', 'Rabito', 'piano', 'OPTIMAL'),
        ('Un pacto con Dios', 'Rabito', 'voz_femenina', 'OPTIMAL'),
        ('Un pacto con Dios', 'Rabito', 'violin_1', 'OPTIMAL'),
        ('Alianza Eterna', 'Hermana Glenda', 'piano', 'MINIMUM'),
        ('Alianza Eterna', 'Hermana Glenda', 'voz_femenina', 'MINIMUM'),
        ('Alianza Eterna', 'Hermana Glenda', 'piano', 'OPTIMAL'),
        ('Alianza Eterna', 'Hermana Glenda', 'voz_femenina', 'OPTIMAL'),
        ('Nadie te ama como yo', 'Martín Valverde', 'piano', 'MINIMUM'),
        ('Nadie te ama como yo', 'Martín Valverde', 'voz_femenina', 'MINIMUM'),
        ('Nadie te ama como yo', 'Martín Valverde', 'piano', 'OPTIMAL'),
        ('Nadie te ama como yo', 'Martín Valverde', 'voz_femenina', 'OPTIMAL'),
        ('Cerca de ti, Señor', 'Tradicional', 'piano', 'MINIMUM'),
        ('Cerca de ti, Señor', 'Tradicional', 'voz_femenina', 'MINIMUM'),
        ('Cerca de ti, Señor', 'Tradicional', 'piano', 'OPTIMAL'),
        ('Cerca de ti, Señor', 'Tradicional', 'voz_femenina', 'OPTIMAL'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Nada te turbe', 'Comunidad de Taizé', 'piano', 'MINIMUM'),
        ('Nada te turbe', 'Comunidad de Taizé', 'voz_femenina', 'MINIMUM'),
        ('Nada te turbe', 'Comunidad de Taizé', 'piano', 'OPTIMAL'),
        ('Nada te turbe', 'Comunidad de Taizé', 'voz_femenina', 'OPTIMAL'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'piano', 'MINIMUM'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'voz_femenina', 'MINIMUM'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'piano', 'OPTIMAL'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'voz_femenina', 'OPTIMAL'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Madre del amor', 'Cristóbal Fones', 'piano', 'MINIMUM'),
        ('Madre del amor', 'Cristóbal Fones', 'voz_femenina', 'MINIMUM'),
        ('Madre del amor', 'Cristóbal Fones', 'piano', 'OPTIMAL'),
        ('Madre del amor', 'Cristóbal Fones', 'voz_femenina', 'OPTIMAL'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'piano', 'MINIMUM'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'voz_femenina', 'MINIMUM'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'piano', 'OPTIMAL'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'voz_femenina', 'OPTIMAL'),
        ('María de la Alianza', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('María de la Alianza', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('María de la Alianza', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('María de la Alianza', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('María, mírame', 'Tradicional litúrgico', 'piano', 'MINIMUM'),
        ('María, mírame', 'Tradicional litúrgico', 'voz_femenina', 'MINIMUM'),
        ('María, mírame', 'Tradicional litúrgico', 'piano', 'OPTIMAL'),
        ('María, mírame', 'Tradicional litúrgico', 'voz_femenina', 'OPTIMAL'),
        ('Salve Regina', 'Canto Gregoriano', 'piano', 'MINIMUM'),
        ('Salve Regina', 'Canto Gregoriano', 'voz_femenina', 'MINIMUM'),
        ('Salve Regina', 'Canto Gregoriano', 'piano', 'OPTIMAL'),
        ('Salve Regina', 'Canto Gregoriano', 'voz_femenina', 'OPTIMAL'),
        ('Salve Regina', 'Canto Gregoriano', 'violin_1', 'OPTIMAL'),
        ('Ave María', 'Giulio Caccini', 'piano', 'MINIMUM')

    INSERT INTO @reqs(titulo, autor, slug_inst, tipo) VALUES
        ('Ave María', 'Giulio Caccini', 'voz_femenina', 'MINIMUM'),
        ('Ave María', 'Giulio Caccini', 'piano', 'OPTIMAL'),
        ('Ave María', 'Giulio Caccini', 'voz_femenina', 'OPTIMAL'),
        ('Ave María', 'Giulio Caccini', 'violin_1', 'OPTIMAL'),
        ('Ave María', 'Giulio Caccini', 'cello', 'OPTIMAL'),
        ('Senza Catene', 'Il Divo', 'piano', 'MINIMUM'),
        ('Senza Catene', 'Il Divo', 'voz_femenina', 'MINIMUM'),
        ('Senza Catene', 'Il Divo', 'piano', 'OPTIMAL'),
        ('Senza Catene', 'Il Divo', 'voz_femenina', 'OPTIMAL'),
        ('Senza Catene', 'Il Divo', 'violin_1', 'OPTIMAL'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'piano', 'MINIMUM'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'voz_femenina', 'MINIMUM'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'piano', 'OPTIMAL'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'voz_femenina', 'OPTIMAL'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'violin_1', 'OPTIMAL'),
        ('Serenata', 'Franz Schubert', 'piano', 'MINIMUM'),
        ('Serenata', 'Franz Schubert', 'voz_femenina', 'MINIMUM'),
        ('Serenata', 'Franz Schubert', 'piano', 'OPTIMAL'),
        ('Serenata', 'Franz Schubert', 'voz_femenina', 'OPTIMAL'),
        ('Serenata', 'Franz Schubert', 'violin_1', 'OPTIMAL'),
        ('Algo contigo', 'Rita Páez', 'piano', 'MINIMUM'),
        ('Algo contigo', 'Rita Páez', 'voz_femenina', 'MINIMUM'),
        ('Algo contigo', 'Rita Páez', 'piano', 'OPTIMAL'),
        ('Algo contigo', 'Rita Páez', 'voz_femenina', 'OPTIMAL'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'piano', 'MINIMUM'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'voz_femenina', 'MINIMUM'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'piano', 'OPTIMAL'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'voz_femenina', 'OPTIMAL'),
        ('Birds of a Feather', 'Billie Eilish', 'piano', 'MINIMUM'),
        ('Birds of a Feather', 'Billie Eilish', 'voz_femenina', 'MINIMUM'),
        ('Birds of a Feather', 'Billie Eilish', 'piano', 'OPTIMAL'),
        ('Birds of a Feather', 'Billie Eilish', 'voz_femenina', 'OPTIMAL'),
        ('Bubbly', 'Colbie Caillat', 'piano', 'MINIMUM'),
        ('Bubbly', 'Colbie Caillat', 'voz_femenina', 'MINIMUM'),
        ('Bubbly', 'Colbie Caillat', 'piano', 'OPTIMAL'),
        ('Bubbly', 'Colbie Caillat', 'voz_femenina', 'OPTIMAL'),
        ('Close to You', 'Carpenters', 'piano', 'MINIMUM'),
        ('Close to You', 'Carpenters', 'voz_femenina', 'MINIMUM'),
        ('Close to You', 'Carpenters', 'piano', 'OPTIMAL'),
        ('Close to You', 'Carpenters', 'voz_femenina', 'OPTIMAL'),
        ('Dream a Little Dream of Me', 'Doris Day', 'piano', 'MINIMUM'),
        ('Dream a Little Dream of Me', 'Doris Day', 'voz_femenina', 'MINIMUM'),
        ('Dream a Little Dream of Me', 'Doris Day', 'piano', 'OPTIMAL'),
        ('Dream a Little Dream of Me', 'Doris Day', 'voz_femenina', 'OPTIMAL'),
        ('Eres para mí', 'Julieta Venegas', 'piano', 'MINIMUM'),
        ('Eres para mí', 'Julieta Venegas', 'voz_femenina', 'MINIMUM'),
        ('Eres para mí', 'Julieta Venegas', 'piano', 'OPTIMAL'),
        ('Eres para mí', 'Julieta Venegas', 'voz_femenina', 'OPTIMAL'),
        ('Es por ti', 'Juanes', 'piano', 'MINIMUM'),
        ('Es por ti', 'Juanes', 'voz_femenina', 'MINIMUM'),
        ('Es por ti', 'Juanes', 'piano', 'OPTIMAL'),
        ('Es por ti', 'Juanes', 'voz_femenina', 'OPTIMAL'),
        ('From the Start', 'Laufey', 'piano', 'MINIMUM'),
        ('From the Start', 'Laufey', 'voz_femenina', 'MINIMUM'),
        ('From the Start', 'Laufey', 'piano', 'OPTIMAL'),
        ('From the Start', 'Laufey', 'voz_femenina', 'OPTIMAL'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'piano', 'MINIMUM'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'voz_femenina', 'MINIMUM'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'piano', 'OPTIMAL'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'voz_femenina', 'OPTIMAL'),
        ('Juntos', 'Paloma San Basilio', 'piano', 'MINIMUM'),
        ('Juntos', 'Paloma San Basilio', 'voz_femenina', 'MINIMUM'),
        ('Juntos', 'Paloma San Basilio', 'piano', 'OPTIMAL'),
        ('Juntos', 'Paloma San Basilio', 'voz_femenina', 'OPTIMAL'),
        ('More Than Words', 'Extreme', 'piano', 'MINIMUM'),
        ('More Than Words', 'Extreme', 'voz_femenina', 'MINIMUM'),
        ('More Than Words', 'Extreme', 'piano', 'OPTIMAL'),
        ('More Than Words', 'Extreme', 'voz_femenina', 'OPTIMAL'),
        ('She Will Be Loved', 'Maroon 5', 'piano', 'MINIMUM'),
        ('She Will Be Loved', 'Maroon 5', 'voz_femenina', 'MINIMUM'),
        ('She Will Be Loved', 'Maroon 5', 'piano', 'OPTIMAL'),
        ('She Will Be Loved', 'Maroon 5', 'voz_femenina', 'OPTIMAL'),
        ('True Colors', 'Cyndi Lauper', 'piano', 'MINIMUM'),
        ('True Colors', 'Cyndi Lauper', 'voz_femenina', 'MINIMUM'),
        ('True Colors', 'Cyndi Lauper', 'piano', 'OPTIMAL'),
        ('True Colors', 'Cyndi Lauper', 'voz_femenina', 'OPTIMAL'),
        ('Unforgettable', 'Nat King Cole', 'piano', 'MINIMUM'),
        ('Unforgettable', 'Nat King Cole', 'voz_femenina', 'MINIMUM'),
        ('Unforgettable', 'Nat King Cole', 'piano', 'OPTIMAL'),
        ('Unforgettable', 'Nat King Cole', 'voz_femenina', 'OPTIMAL'),
        ('Yo quisiera', 'Reik', 'piano', 'MINIMUM'),
        ('Yo quisiera', 'Reik', 'voz_femenina', 'MINIMUM'),
        ('Yo quisiera', 'Reik', 'piano', 'OPTIMAL'),
        ('Yo quisiera', 'Reik', 'voz_femenina', 'OPTIMAL'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'piano', 'MINIMUM'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'voz_femenina', 'MINIMUM'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'piano', 'OPTIMAL'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'voz_femenina', 'OPTIMAL'),
        ('One of Us', 'Joan Osborne', 'piano', 'MINIMUM'),
        ('One of Us', 'Joan Osborne', 'voz_femenina', 'MINIMUM'),
        ('One of Us', 'Joan Osborne', 'piano', 'OPTIMAL'),
        ('One of Us', 'Joan Osborne', 'voz_femenina', 'OPTIMAL')

    INSERT INTO cancion_requerimiento(id_cancion, id_instrumento, tipo)
    SELECT s.id_cancion, i.id_instrumento, r.tipo
    FROM @reqs r
    INNER JOIN cancion s ON s.titulo = r.titulo AND s.autor = r.autor
    INNER JOIN instrumento i ON i.slug = r.slug_inst
END
GO

PRINT 'Requerimientos cargados: ' + CAST((SELECT COUNT(*) FROM cancion_requerimiento) AS VARCHAR)
GO
