-- =============================================================================
-- 11_seed_song_styles.sql
-- Estilos musicales por cancion.
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM cancion_estilo)
BEGIN
    DECLARE @sts TABLE (titulo VARCHAR(256), autor VARCHAR(256), estilo VARCHAR(20))

    INSERT INTO @sts(titulo, autor, estilo) VALUES
        ('Canon en Re mayor', 'Johann Pachelbel', 'CLASSICAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'CLASSICAL'),
        ('Pie Jesu', 'Andrew Lloyd Webber', 'LYRICAL'),
        ('Ave María', 'Franz Schubert', 'CLASSICAL'),
        ('Ave María', 'Franz Schubert', 'LYRICAL'),
        ('Ave María', 'Verbum Panis', 'CONTEMPORARY'),
        ('Ave María', 'Verbum Panis', 'LYRICAL'),
        ('Perfect', 'Ed Sheeran', 'MODERN'),
        ('A Thousand Years', 'Christina Perri', 'MODERN'),
        ('A Thousand Years', 'Christina Perri', 'LYRICAL'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'MODERN'),
        ('Hallelujah (Aleluya de Bodas)', 'Leonard Cohen', 'LYRICAL'),
        ('Arrival of the Queen of Sheba', 'G.F. Haendel', 'CLASSICAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'CLASSICAL'),
        ('Oboe de Gabriel (La Misión)', 'Ennio Morricone', 'LYRICAL'),
        ('Adagio en Sol menor', 'Tomaso Albinoni', 'CLASSICAL'),
        ('Minueto en Sol', 'Luigi Boccherini', 'CLASSICAL'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'CLASSICAL'),
        ('Sublime Gracia (Amazing Grace)', 'John Newton', 'LYRICAL'),
        ('Delante del altar', 'Joel Cruz', 'CONTEMPORARY'),
        ('Aclaró', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Por ti volaré (Con te partirò)', 'Andrea Bocelli', 'LYRICAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'CLASSICAL'),
        ('O mio babbino caro', 'Giacomo Puccini', 'LYRICAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'CLASSICAL'),
        ('Nessun Dorma (Turandot)', 'Giacomo Puccini', 'LYRICAL'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'CLASSICAL'),
        ('Lascia ch''io pianga', 'G.F. Haendel', 'LYRICAL'),
        ('Meditación de Thaïs', 'Jules Massenet', 'CLASSICAL'),
        ('Intermezzo (Cavalleria Rusticana)', 'Pietro Mascagni', 'CLASSICAL'),
        ('Rivers Flows in You', 'Yiruma', 'MODERN'),
        ('Rivers Flows in You', 'Yiruma', 'LYRICAL'),
        ('Only Time', 'Enya', 'MODERN'),
        ('Only Time', 'Enya', 'LYRICAL'),
        ('Ven amada mía', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'CLASSICAL'),
        ('Dúo de las Flores (Ópera Lakmé)', 'Léo Delibes', 'LYRICAL'),
        ('Hoy perdóname', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Oh Santo Dios', 'Tradicional litúrgico', 'CLASSICAL'),
        ('Señor ten piedad (C. Fones)', 'Cristóbal Fones', 'CONTEMPORARY'),
        ('Una vez más rezaré', 'Comunidad Schoenstatt', 'CONTEMPORARY'),
        ('Traigo, Señor, otra vez', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Ten piedad de mí, oh Dios', 'Tradicional litúrgico', 'CLASSICAL'),
        ('Por el mundo, por la paz', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Gloria (Misa Criolla)', 'Ariel Ramírez', 'CONTEMPORARY'),
        ('Gloria (Taizé)', 'Jacques Berthier', 'CONTEMPORARY'),
        ('El Señor es mi pastor (Salmo 22)', 'Tradicional litúrgico', 'CLASSICAL'),
        ('Felices los que temen al Señor (Salmo 127)', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Tú que habitas (Salmo 91)', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Dichoso quien ama de corazón', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Aclama al Señor, tierra entera (Salmo 100)', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Aleluya (El Mesías)', 'G.F. Haendel', 'CLASSICAL'),
        ('Aleluya toda la tierra (Pascual)', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Amarte a ti, Señor', 'Cristóbal Fones', 'CONTEMPORARY'),
        ('Aún en la tormenta', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Dios está aquí', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('No me eligieron ustedes', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Cuando en la mañana sale el sol', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Laudate Omnes Gentes', 'Comunidad de Taizé', 'CLASSICAL'),
        ('No fijéis los ojos', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Oración por la Familia', 'Padre Zezinho', 'CONTEMPORARY'),
        ('Hoy queremos ofrecerte, Señor', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('El Señor nos ha reunido junto a Él', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Ante tu altar', 'Walmir Alencar', 'CONTEMPORARY'),
        ('Tal como soy, Señor', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Bendito seas, Señor', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Cinco panes', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Esto que soy, esto te doy', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Ave Verum Corpus', 'W.A. Mozart', 'CLASSICAL'),
        ('Tómame', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Juntos nos acercamos', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Sanctus (Gounod)', 'Charles Gounod', 'CLASSICAL'),
        ('Sanctus (Schubert)', 'Franz Schubert', 'CLASSICAL'),
        ('Santo es el Señor (C. Fones)', 'Cristóbal Fones', 'CONTEMPORARY'),
        ('Santo al Hijo de David', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Santo (Misa Criolla)', 'Ariel Ramírez', 'CONTEMPORARY'),
        ('Santo — Hosanna', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Cordero de Dios (C. Fones)', 'Cristóbal Fones', 'CONTEMPORARY'),
        ('Dona Nobis Pacem', 'Canto tradicional', 'CLASSICAL'),
        ('Un pacto con Dios', 'Rabito', 'CONTEMPORARY'),
        ('Alianza Eterna', 'Hermana Glenda', 'CONTEMPORARY'),
        ('Nadie te ama como yo', 'Martín Valverde', 'CONTEMPORARY'),
        ('Cerca de ti, Señor', 'Tradicional', 'CLASSICAL'),
        ('Espíritu de Dios', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Espíritu Santo, Ven', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Jesús estoy aquí', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Nada te turbe', 'Comunidad de Taizé', 'CONTEMPORARY'),
        ('Señor, a quién iremos', 'Cesáreo Gabaráin', 'CONTEMPORARY'),
        ('Comiendo del mismo pan', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('El peregrino de Emaús', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('En mi Getsemaní', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Maravillas hizo en mí', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Madre del amor', 'Cristóbal Fones', 'CONTEMPORARY'),
        ('Dios te salve, María', 'Tradicional litúrgico', 'CLASSICAL'),
        ('Santa María del Camino', 'Cesáreo Gabaráin', 'CONTEMPORARY'),
        ('María de la Alianza', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('El Señor hizo en mí maravillas (Magnificat)', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('María, mírame', 'Tradicional litúrgico', 'CONTEMPORARY'),
        ('Salve Regina', 'Canto Gregoriano', 'CLASSICAL'),
        ('Ave María', 'Giulio Caccini', 'CLASSICAL'),
        ('Ave María', 'Giulio Caccini', 'LYRICAL'),
        ('Senza Catene', 'Il Divo', 'LYRICAL'),
        ('Memory (Cats)', 'Andrew Lloyd Webber', 'LYRICAL'),
        ('Serenata', 'Franz Schubert', 'CLASSICAL'),
        ('Serenata', 'Franz Schubert', 'LYRICAL'),
        ('Algo contigo', 'Rita Páez', 'LYRICAL'),
        ('Baby Can I Hold You', 'Tracy Chapman', 'LYRICAL'),
        ('Birds of a Feather', 'Billie Eilish', 'MODERN'),
        ('Bubbly', 'Colbie Caillat', 'MODERN'),
        ('Close to You', 'Carpenters', 'CLASSICAL'),
        ('Dream a Little Dream of Me', 'Doris Day', 'CLASSICAL'),
        ('Eres para mí', 'Julieta Venegas', 'MODERN'),
        ('Es por ti', 'Juanes', 'MODERN'),
        ('From the Start', 'Laufey', 'MODERN'),
        ('From the Start', 'Laufey', 'LYRICAL'),
        ('Hasta la raíz', 'Natalia Lafourcade', 'LYRICAL'),
        ('Juntos', 'Paloma San Basilio', 'LYRICAL'),
        ('More Than Words', 'Extreme', 'LYRICAL'),
        ('She Will Be Loved', 'Maroon 5', 'MODERN'),
        ('True Colors', 'Cyndi Lauper', 'LYRICAL'),
        ('Unforgettable', 'Nat King Cole', 'CLASSICAL'),
        ('Yo quisiera', 'Reik', 'MODERN'),
        ('Can''t Take My Eyes Off You', 'Frankie Valli', 'CLASSICAL'),
        ('One of Us', 'Joan Osborne', 'MODERN')

    INSERT INTO cancion_estilo(id_cancion, estilo)
    SELECT s.id_cancion, st.estilo
    FROM @sts st
    INNER JOIN cancion s ON s.titulo = st.titulo AND s.autor = st.autor
END
GO
